before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

image: gradle:7.6.0-jdk19-alpine

stages:
  - test

test:
  stage: test
  script: ./gradlew test
  artifacts:
    reports:
      junit:
        - app/build/test-results/test/TEST-*.xml
