before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

image: jenkins/jnlp-slave:latest

stages:
  - test

test:
  stage: test
  script:
    - export DISPLAY=:0
    - ./gradlew test
  artifacts:
    reports:
      junit:
        - app/build/test-results/test/TEST-*.xml
