/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controller;

import java.util.Timer;

import javax.swing.JFrame;

import model.Ball;
import model.Brick;
import model.Paddle;
import utils.FrameCommons;
import view.BallView;
import view.BrickView;
import view.GamePanel;
import view.GameUI;
import view.PaddleAdapter;
import view.PaddleView;

public class App {
  public static void main(String[] args) {
    final int NO_OF_BRICKS = 50;

    JFrame frame = new JFrame();
    Timer timer = new Timer();
    GameObjectFactory objectFactory = new GameObjectFactory();
    GameViewFactory viewFactory = new GameViewFactory();

    Ball ball = objectFactory.createBall();
    Brick[] bricks = objectFactory.createBricks(NO_OF_BRICKS);
    Paddle paddle = objectFactory.createPaddle();

    BallView ballView = viewFactory.createBallView(ball);
    BrickView[] brickViews = viewFactory.createBrickViews(bricks);
    PaddleView paddleView = viewFactory.createPaddleView(paddle);

    GamePanel gamePanel = new GamePanel(ballView, brickViews, paddleView);
    PaddleAdapter paddleAdapter = new PaddleAdapter(paddle);

    GameUI gameUI = new GameUI(frame, FrameCommons.WIDTH, FrameCommons.HEIGHT, paddleAdapter, gamePanel);

    Game game = new Game(ball, bricks, paddle, gameUI, timer);
    game.start();
  }
}
