/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controller;

// import javax.swing.JFrame;

// import view.GameUI;

public class App {
  public static void main(String[] args) {
    // GameUI gameUI = new GameUI(new JFrame());
  }
}
