/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package controller;

import javax.swing.JFrame;

import model.Ball;
import model.Brick;
import model.Paddle;
import view.BallView;
import view.BrickView;
import view.GamePanel;
import view.GameUI;
import view.PaddleView;

public class App {
  public static void main(String[] args) {
    GameUI gameUI = new GameUI(new JFrame(), 800, 800, new GamePanel(new BallView(new Ball()), new BrickView(new Brick()), new PaddleView(new Paddle())));
  }
}
